<div id="lay-container">
    <div class="image-slider-wrapper">
                <div class="image-slider-inner">
                    <div class="image-slider-item">
                        <picture>
                            <source media="(max-width:601px)" srcset="img/me.jpg">
                            <source media="(max-width:1025px)" srcset="http://unsplash.it/1024/768/?img=1000">
                            <img src="http://unsplash.it/3440/1440/?img=1000">
                        </picture>
                        <div class="slider-caption">
                            <p class="caption animated rotateIn ">Created by Do Trung Hieu</p>
                        </div>
                    </div>
                    <div class="image-slider-item">
                        <picture>
                            <source media="(max-width:601px)" srcset="http://unsplash.it/800/600/?img=1001">
                            <source media="(max-width:1025px)" srcset="http://unsplash.it/1024/768/?img=1001">
                            <img src="http://unsplash.it/3440/1440/?img=1001">
                        </picture>
                        <div class="slider-caption">
                            <p class="caption animated lightSpeedIn ">The Best Park In The World</p>
                        </div>
                    </div>
                    <div class="image-slider-item">
                        <picture>
                            <source media="(max-width:601px)" srcset="http://unsplash.it/800/600/?img=1002">
                            <source media="(max-width:1025px)" srcset="http://unsplash.it/1024/768/?img=1002">
                            <img src="http://unsplash.it/3440/1440/?img=1002">
                        </picture>
                        <div class="slider-caption">
                            <p class="caption animated fadeInUp">Enjoy the ride !</p>
                        </div>
                    </div>
                    <div class="image-slider-item">
                        <picture>
                            <source media="(max-width:601px)" srcset="http://unsplash.it/800/600/?img=1003">
                            <source media="(max-width:1025px)" srcset="http://unsplash.it/1024/768/?img=1003">
                            <img src="http://unsplash.it/3440/1440/?img=1003">
                        </picture>
                        <div class="slider-caption">
                            <p class="caption animated zoomIn  ">Experience of a lifetime</p>
                        </div>
                    </div>
                    <div class="image-slider-item">
                        <picture>
                            <source media="(max-width:601px)" srcset="http://unsplash.it/800/600/?img=1004">
                            <source media="(max-width:1025px)" srcset="http://unsplash.it/1024/768/?img=1004">
                            <img src="http://unsplash.it/3440/1440/?img=1004">
                        </picture>
                        <div class="slider-caption">
                            <p class="caption animated bounceInDown">Available for all ages</p>
                        </div>
                    </div>
                    <div class="image-slider-item">
                        <picture>
                            <source media="(max-width:601px)" srcset="http://unsplash.it/800/600/?img=1005">
                            <source media="(max-width:1025px)" srcset="http://unsplash.it/1024/768/?img=1005">
                            <img src="http://unsplash.it/3440/1440/?img=1005">
                        </picture>
                        <div class="slider-caption">
                            <p class="caption animated flipInX ">Memorable, Fun, and affordable </p>
                        </div>
                    </div>
                    <!-- controler -->
                    <button class="slider-control" id="prevButton">&lt;</button>
                    <button class="slider-control" id="nextButton">&GT;</button>
                    <!-- indicator -->
                    <div class="slider-indicators">
                        <button class="slider-indicator"></button>
                        <button class="slider-indicator"></button>
                        <button class="slider-indicator"></button>
                        <button class="slider-indicator"></button>
                        <button class="slider-indicator"></button>
                        <button class="slider-indicator"></button>
                    </div>
     </div>
    </div>
<div id="lay-about" >
	<div class="lay-2col lay-bg to-animate-2" style="background-image: url(/mywebsite.com/public/img/res_img_1.jpg)"></div>
	<div class="lay-2col lay-text">
		<h2 class="heading to-animate">About Us</h2>
		<p class="to-animate"><span class="firstcharacter">W</span>ith the long Fourth of July weekend coming up, I bet at least some of our _flossy readers are headed to an amusement park to celebrate with roller coasters, cotton candy and water slides. So to give you some food for thought while you're waiting to ride the Scrambler, here are a few random facts about the parks that keep us entertained..</p>
		<p class="to-animate text-center"><a href="/mywebsite.com/about" data-nav-section="events" class=" homepage-readmore btn btn-primary btn-outline">READ MORE</a></p>
	</div>
</div>
<div id="lay-sayings">
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
	 	<div class="carousel-inner">
		    <div class="carousel-item active">
				<h3><i>&ldquo;A lot of fascinating games.&rdquo;</i></h3>
		    </div>
		    <div class="carousel-item">
		    	<h3><i>&ldquo;Adventure with friends.&rdquo;</i></h3>
		    </div>
		    <div class="carousel-item">
		      	<h3><i>&ldquo;Family entertainment place.&rdquo;</i></h3>
		    </div>
		</div>
  	</div>
</div>
<div id="lay-featured">
	<div class="container">
		<div class="row text-center lay-heading row-padded">
			<div class="col-12">
				<h2 class="heading to-animate">Play Zone</h2>
				<p class="sub-heading to-animate">A lot of fascinating games</p>
			</div>
		</div>
		<div class="row">
			<div class="lay-grid">
				<div class="lay-v-half to-animate-2">
					<div class="lay-v-col-2 lay-bg-img" style="background-image: url(/mywebsite.com/public/img/res_img_1.jpg)"></div>
					<div class="lay-v-col-2 lay-text lay-special-1 arrow-left">
						<h2>Water pool</h2>
						<span class="pricing"></span>
						<p>unleash with the country's largest artificial pool</p>
					</div>
				</div>
				<div class="lay-v-half">
					<div class="lay-h-row-2 to-animate-2">
						<div class="lay-v-col-2 lay-bg-img" style="background-image: url(/mywebsite.com/public/img/res_img_2.jpg)"></div>
						<div class="lay-v-col-2 lay-text arrow-left">
							<h2>roller coaster</h2>
							<span class="pricing"></span>
							<p>adventure with friends from a height of 2000m</p>
						</div>
					</div>
					<div class="lay-h-row-2 lay-reversed to-animate-2">
						<div class="lay-v-col-2 lay-bg-img" style="background-image: url(/mywebsite.com/public/img/res_img_8.jpg)"></div>
						<div class="lay-v-col-2 lay-text arrow-right">
							<h2>float home</h2>
							<span class="pricing"></span>
							<p>family entertainment place</p>
						</div>
					</div>
				</div>

				<div class="lay-v-half">
					<div class="lay-h-row-2 lay-reversed to-animate-2">
						<div class="lay-v-col-2 lay-bg-img" style="background-image: url(/mywebsite.com/public/img/res_img_7.jpg)"></div>
						<div class="lay-v-col-2 lay-text arrow-right">
							<h2>Ferris adventure</h2>
							<span class="pricing"></span>
							<p>Try thrilling with level 5 games</p>
						</div>
					</div>
					<div class="lay-h-row-2 to-animate-2">
						<div class="lay-v-col-2 lay-bg-img" style="background-image: url(/mywebsite.com/public/img/res_img_6.jpg)"></div>
						<div class="lay-v-col-2 lay-text arrow-left">
							<h2>adventurous cable car</h2>
							<span class="pricing"></span>
							<p>Try feeling strong</p>
						</div>
					</div>
				</div>
				<div class="lay-v-half to-animate-2">
					<div class="lay-v-col-2 lay-bg-img" style="background-image: url(/mywebsite.com/public/img/res_img_3.jpg)"></div>
					<div class="lay-v-col-2 lay-text lay-special-1 arrow-left">
						<h2>Ferris</h2>
						<span class="pricing"></span>
						<p>Enjoy the view of the city above</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="lay-type" style="background-image: url(/mywebsite.com/public/img/slide_3.jpg);" >
	<div class="lay-overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-3 to-animate">
				<div class="lay-type">
					<h3 class="with-icon icon-1">Water park</h3>
					<p>Enjoy relaxing moments at the hot springs</p>
				</div>
			</div>
			<div class="col-md-3 to-animate">
				<div class="lay-type">
					<h3 class="with-icon icon-2">Park</h3>
					<p>First-class entertainment area</p>
				</div>
			</div>
			<div class="col-md-3 to-animate">
				<div class="lay-type">
					<h3 class="with-icon icon-3">Telepheric.</h3>
					<p>See the spectacular natural scenery</p>
				</div>
			</div>
			<div class="col-md-3 to-animate">
				<div class="lay-type">
					<h3 class="with-icon icon-4">Restaurant</h3>
					<p>service experience of trendy 5-star hotels</p>
				</div>
			</div>
		</div>
	</div>
</div>