</div>
<footer id="lay-footer">
		<div class="container">
			<div class="row row-padded">
				<div class="col-12 text-center">
					<p class="to-animate">
						&copy; 2019 eProject team. <br>
						MERCIARDO AMUSEMENT PARK
					</p>
				</div>
			</div>
			<div class="row">
				<div class="col-12 text-center">
					<ul class="lay-social">
						<li class="to-animate-2"><a href="#"><i class="fab fa-facebook-square"></i></a></li>
						<li class="to-animate-2"><a href="#"><i class="fab fa-twitter-square"></i></a></li>
						<li class="to-animate-2"><a href="#"><i class="fab fa-instagram"></i></a></li>
					</ul>
				</div>
			</div>
			<a href="javascript:" id="return-to-top"><i class="fas fa-angle-up"></i></a>
		</div>
	</footer>
    </body>
</html>


