<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" 
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?= $this->viewData["pageTitle"] ?? 'error' ?></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<link href="/mywebsite.com/public/css/animation.css" rel="stylesheet" type="text/css"/>
        <link href="/mywebsite.com/public/css/main.css" rel="stylesheet" type="text/css"/>
        <link href="/mywebsite.com/public/css/ticket.css" rel="stylesheet" type="text/css"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
	<script async src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="/mywebsite.com/public/js/carousel.js" type="text/javascript"></script>
        <script src="/mywebsite.com/public/js/carousel-detail.js" type="text/javascript"></script>
        <script async src="/mywebsite.com/public/js/script.js" type="text/javascript"></script>        
        <script src="/mywebsite.com/public/js/autocomplete.js" type="text/javascript"></script>
    </head>
    <body> 
        <ul class="topnav">
          <li><a id="home"
                 href="http://localhost:81/mywebsite.com/home" 
                 class="webpage <?= preg_match("/home/",$this->viewName) ? "active" : '' ?>"
                 >Home</a></li>
          <li><a href="http://localhost:81/mywebsite.com/restaurants" 
                 class="webpage <?= preg_match("/restaurants/",$this->viewName) ? "active" : ''?>"
                 id="restaurant">Restaurants</a></li>
          <li><a href="http://localhost:81/mywebsite.com/amusement" 
                 class="webpage <?= preg_match("/amusement/",$this->viewName) ? "active" : '' ?>"
                 id="amusement">Amusement</a></li>
          <li><a href="http://localhost:81/mywebsite.com/about" 
                 class="webpage <?= preg_match("/about/",$this->viewName) ? "active" : '' ?>"
                 id="about">About</a></li>
           <li><a href="http://localhost:81/mywebsite.com/contact" 
                 class="webpage <?= preg_match("/contact/",$this->viewName) ? "active" : '' ?>"
                 id="contact">Contact</a></li>
          <form action="" method="POST">
              <input type="text" placeholder="username..." name="login-uName">
              <input type="text" name="login-pass" placeholder="pass...">
              <input type="submit" name="login-submit" value="login">
              <button type="button"><a href="#">Sign up</a></button>
              <button type="button"><a href="#">Forget pass ?</a></button>
          </form>       
        </ul>   
        <div class="page-content">
  

