<div class="amusement-item-title">
	<i class="fas fa-star star-one"></i>
	<i class="fas fa-star star-two"></i>
	<i class="fas fa-star star-three"></i>
	<h1>Les Tasses spinning cans</h1>
	<i class="fas fa-star star-three"></i>
	<i class="fas fa-star star-two"></i>
	<i class="fas fa-star star-one"></i>	
</div>
<div class="amusement-item">
	<div class="container">
		<div class="row">
			<div class="col-md-7 col-12">
				<div id="carousel" class="carousel slide" data-ride="carousel">
				  <div class="carousel-inner">
				    <div class="carousel-item active">
				      <img class="d-block w-100" src="img/item1.jpg" >
				    </div>
				    <div class="carousel-item">
				      <img class="d-block w-100" src="img/item2.jpg" >
				    </div>
				    <div class="carousel-item">
				      <img class="d-block w-100" src="img/item3.jpg" >
				    </div>
				  </div>
				  <div class="carousel-indicator">
				  	<span class="carousel-indicator-item-1">
				  		<i class="fas fa-circle" class="active"></i>
				  	</span>
				  	<span class="carousel-indicator-item-2">
				  		<i class="fas fa-circle" ></i>
				  	</span>
				  	<span class="carousel-indicator-item-3">
				  		<i class="fas fa-circle" ></i>
				  	</span>
				  </div>
				</div>
			</div>
			<div class="col-md-5 col-12 amusement-item-text">
				<p>Adventurers Club is in Plaça Tibidabo in front of the main entrance, serving a wide range of salads, tapas and sandwiches. It has a terrace, indoor dining room with air conditioning and Wi-Fi.</p>
				<p><strong>Opening times:</strong> from 10am until the Park and/or Panorcamic Area closes.</p><br>
				<p>Also, from 10.30 am to 11.30 am, enjoy its breakfast offer for only €3,50: toasted cheese and ham sandwich + coffee or coffee with milk (only available when the amusement park opens).</p>
				<p>Nivell 6</p>
			</div>
		</div>
	</div>
</div>
