<?php $info = $this->viewData["detail"][0]?>
<div class="amusement-item-title">
	<i class="fas fa-star star-one"></i>
	<i class="fas fa-star star-two"></i>
	<i class="fas fa-star star-three"></i>
        <h1><?= $info["name"]?></h1>
	<i class="fas fa-star star-three"></i>
	<i class="fas fa-star star-two"></i>
	<i class="fas fa-star star-one"></i>	
</div>
<div class="amusement-item">
	<div class="container">
		<div class="row">
			<div class="col-md-7 col-12">
				<div id="carousel" class="carousel slide" data-ride="carousel">
				  <div class="carousel-inner">
				    <div class="carousel-item active">
                                        <img class="d-block w-100" src="/mywebsite.com/public/image/amusement/<?= $info["urlName"] ?>/1.jpg" >
				    </div>
				    <div class="carousel-item">
				      <img class="d-block w-100" src="/mywebsite.com/public/image/amusement/<?= $info["urlName"] ?>/2.jpg" >
				    </div>
				    <div class="carousel-item">
				      <img class="d-block w-100" src="/mywebsite.com/public/image/amusement/<?=$info["urlName"] ?>/3.jpg" >
				    </div>
				  </div>
				  <div class="carousel-indicator">
				  	<span class="carousel-indicator-item-1">
				  		<i class="fas fa-circle" class="active"></i>
				  	</span>
				  	<span class="carousel-indicator-item-2">
				  		<i class="fas fa-circle" ></i>
				  	</span>
				  	<span class="carousel-indicator-item-3">
				  		<i class="fas fa-circle" ></i>
				  	</span>
				  </div>
				</div>
			</div>
			<div class="col-md-5 col-12 amusement-item-text">
                            <p><?= $info["description"] ?></p>
                            <p><strong>Height restrictions</strong></p>
                            <?php foreach(explode(",", $info["height"]) as $heights):?>
                            <p><?= $heights ?></p>
                            <?php endforeach; ?>
			</div>
		</div>
	</div>
</div>
