<div class="amusement">
	<div class="container">
		<div class="row">
			<div class="col-md-3 col-12">
				<ul>
                                    <li class="search-bar">
                                        <form autocomplete="off" id="Amusement" class="search-form" action="http://localhost:81/mywebsite.com/restaurants" method="POST">
                                            <input type="text" placeholder="Search..." name="search" id="search-input">
                                            <button type="submit"><i class="fas fa-search"></i></button>    
                                        </form>						
				    </li>
                                    <div class="autocomplete-container"></div>
					<li class="by-type">
						<h5>BY TYPE</h5>
						<label class="custom-checkbox">Emblematic
							<input type="checkbox" name="Emblematic">
							<span class="checkmark"></span>
						</label>
						<label class="custom-checkbox">Essencial
							<input type="checkbox" name="Essencial">
							<span class="checkmark"></span>
						</label>
						<label class="custom-checkbox">Familiar
							<input type="checkbox" name="Familiar">
							<span class="checkmark"></span>
						</label>
						<label class="custom-checkbox">For children
							<input type="checkbox" name="For children">
							<span class="checkmark"></span>
						</label>
					</li>
					<li class="by-height">
						<h5>BY HEIGHT</h5>
						<div class="extra-wrap">
							<label class="custom-checkbox">Birds
								<input type="checkbox" name="Birds">
								<span class="checkmark"></span>
								<p>0 - 90 cm.</p>
							</label>
						</div>
						<div class="extra-wrap">
							<label class="custom-checkbox">Salamandres
								<input type="checkbox" name="Salamandres">
								<span class="checkmark"></span>
								<p>90 - 120 cm.</p>
							</label>
						</div>
						<div class="extra-wrap">
							<label class="custom-checkbox">Foxes
								<input type="checkbox" name="Foxes">
								<span class="checkmark"></span>
								<p>120 - 130 cm.</p>
							</label>
						</div>
						<div class="extra-wrap">
							<label class="custom-checkbox">Boars
								<input type="checkbox" name="Boars">
								<span class="checkmark"></span>
								<p>+130 cm.</p>
							</label>
						</div>
					</li>
					<li class="by-type">
						<h5>BY LOCATION</h5>
						<label class="custom-checkbox">Level 1
							<input type="checkbox" name="Level-1">
							<span class="checkmark"></span>
						</label>
						<label class="custom-checkbox">Level 2
							<input type="checkbox" name="Level-2">
							<span class="checkmark"></span>
						</label>
						<label class="custom-checkbox disabeled">Level 3 - Staff Acces
							<input type="checkbox" name="Level-3">
							<span class="checkmark disabel" ></span>
						</label>
						<label class="custom-checkbox">Level 4
							<input type="checkbox" name="Level-4">
							<span class="checkmark"></span>
						</label>
						<label class="custom-checkbox">Level 5
							<input type="checkbox" name="Level-5">
							<span class="checkmark"></span>
						</label>
						<label class="custom-checkbox">Level 6
							<input type="checkbox" name="Level-6">
							<span class="checkmark"></span>
						</label>
					</li>
					<button class="btn float-right">Apply</button>
				</ul>
			</div>
			<div class="col-md-9 col-12">
				<div class="row">
					<div class="col-md-4 col-12">
						<a href="#">
							<div class="amusement-main">
							  	<img src="https://via.placeholder.com/40x30" class="amusement-image" style="width:100%">
									<div class="amusement-image-container">
								    	<h4>LES TASSES</h4>
								    	<p>Spin round and round, alone or with the family, in the spinning</p>
								    	<button class="btn">ADD TO MY VISIT</button>
								  	</div>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-12">
						<a href="#">
							<div class="amusement-main">
							  	<img src="https://via.placeholder.com/40x30" class="amusement-image" style="width:100%">
									<div class="amusement-image-container">
								    	<h4>LES TASSES</h4>
								    	<p>Spin round and round, alone or with the family, in the spinning</p>
								    	<button class="btn">ADD TO MY VISIT</button>
								  	</div>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-12">
						<a href="#">
							<div class="amusement-main">
							  	<img src="https://via.placeholder.com/40x30" class="amusement-image" style="width:100%">
									<div class="amusement-image-container">
								    	<h4>LES TASSES</h4>
								    	<p>Spin round and round, alone or with the family, in the spinning</p>
								    	<button class="btn">ADD TO MY VISIT</button>
								  	</div>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-12">
						<a href="#">
							<div class="amusement-main">
							  	<img src="https://via.placeholder.com/40x30" class="amusement-image" style="width:100%">
									<div class="amusement-image-container">
								    	<h4>LES TASSES</h4>
								    	<p>Spin round and round, alone or with the family, in the spinning</p>
								    	<button class="btn">ADD TO MY VISIT</button>
								  	</div>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-12">
						<a href="#">
							<div class="amusement-main">
							  	<img src="https://via.placeholder.com/40x30" class="amusement-image" style="width:100%">
									<div class="amusement-image-container">
								    	<h4>LES TASSES</h4>
								    	<p>Spin round and round, alone or with the family, in the spinning</p>
								    	<button class="btn">ADD TO MY VISIT</button>
								  	</div>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-12">
						<a href="#">
							<div class="amusement-main">
							  	<img src="https://via.placeholder.com/40x30" class="amusement-image" style="width:100%">
									<div class="amusement-image-container">
								    	<h4>LES TASSES</h4>
								    	<p>Spin round and round, alone or with the family, in the spinning</p>
								    	<button class="btn">ADD TO MY VISIT</button>
								  	</div>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-12">
						<a href="#">
							<div class="amusement-main">
							  	<img src="https://via.placeholder.com/40x30" class="amusement-image" style="width:100%">
									<div class="amusement-image-container">
								    	<h4>LES TASSES</h4>
								    	<p>Spin round and round, alone or with the family, in the spinning</p>
								    	<button class="btn">ADD TO MY VISIT</button>
								  	</div>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-12">
						<a href="#">
							<div class="amusement-main">
							  	<img src="https://via.placeholder.com/40x30" class="amusement-image" style="width:100%">
									<div class="amusement-image-container">
								    	<h4>LES TASSES</h4>
								    	<p>Spin round and round, alone or with the family, in the spinning</p>
								    	<button class="btn">ADD TO MY VISIT</button>
								  	</div>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-12">
						<a href="#">
							<div class="amusement-main">
							  	<img src="https://via.placeholder.com/40x30" class="amusement-image" style="width:100%">
									<div class="amusement-image-container">
								    	<h4>LES TASSES</h4>
								    	<p>Spin round and round, alone or with the family, in the spinning</p>
								    	<button class="btn">ADD TO MY VISIT</button>
								  	</div>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
