<?php foreach($this->viewData["info"] as $info): ?>
					<div class="col-md-4 col-12">
                                            <a class="amusement-detail" href="/mywebsite.com/amusement/detail/<?= $info["urlName"] ?>">
							<div class="amusement-main">
                                                            <img src="/mywebsite.com/public/image/amusement/<?= $info["urlName"]?>/1.jpg" class="amusement-image detail" style="width:100%">
									<div class=" detail amusement-image-container">
                                                                        <h4 class="detail"><?= $info["name"]?></h4>
                                                                        <p class="detail"><?= $info["shortDes"]?></p>								    	
								  	</div>
							</div>
						</a>
                                           <?php if($info["quantity"] != 0): ?>
                                                <?php if(!in_array($info["id"],($_SESSION["ticket"] ?? []))):?>
                                                <a  class="btn  ticket-btn add-ticket"
                                                    href="/mywebsite.com/amusement/addticket/?id=<?= $info["id"] ?>">ADD TO MY VISIT</a>
                                                <?php elseif(in_array($info["id"],($_SESSION["ticket"] ?? []))): ?>
                                                <a  class="btn  ticket-btn add-ticket"
                                                    href="/mywebsite.com/amusement/removeticket/?id=<?= $info["id"] ?>">REMOVE FROM MY VISIT</a>
                                                <?php endif;?>
                                            <?php elseif(is_null($info["quantity"])): ?>
                                            <button class="btn  ticket-btn">Free</button>
                                            <?php elseif($info["quantity"] == 0): ?>
                                            <button class="btn  ticket-btn">Out of tickets</button>
                                            <?php endif;?>
					</div>
<?php endforeach;?>
