<div class="middle">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.512788627209!2d105.84218861494861!3d21.01215849372072!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab8ee6df247f%3A0xe6183d662696d2e9!2sUnion+Park!5e0!3m2!1sen!2s!4v1555921337774!5m2!1sen!2s" width="600" height="550" frameborder="0" style="border:0" allowfullscreen></iframe>
	<div class="container">
		<div class="row">
			<div class="col-sm-5 col-12">
				<h2>GET IN TOUCH</h2>
				<h3>ADDRESS 1:</h3>
				<p>8901 Marmora Road, Glasgow, D04 89GR.</p>
				<p>+1 800 559 6580 </p>
				<p>+1 800 559 6580 </p>
				<p>+1 800 559 6580 </p>
				<h3>ADDRESS 2:</h3>
				<p>8901 Marmora Road, Glasgow, D04 89GR.</p>
			</div>
			<div class="col-sm-7 col-12">
				<h2>CONTACT FORM</h2>
				<form>
					<div class="row">
						<div class="col-lg-4 col-12">
							<input type="text" class="form-control" placeholder="Name:">
						</div>
						<div class="col-lg-4 col-12">
							<input type="text" class="form-control" placeholder="Email:">
						</div>
						<div class="col-lg-4 col-12">
							<input type="text" class="form-control" placeholder="Phone:">
						</div>
						<div class="col-12">
							<textarea placeholder="Message:" class="form-control" rows="8"></textarea>
						</div>
						<button type="submit">SUBMIT</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
